apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-cm
  namespace: elastic-system
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-cm
  namespace: elastic-system
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if [kubernetes][container_name] =~ /^dev/ {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} %{GREEDYDATA:message}" }
        }
      }
    }


    output {
      elasticsearch {
        hosts => ["http://10.5.25.7:9200"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        #user => "elastic"
        #password => "changeme"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elastic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash-container
        image: docker.elastic.co/logstash/logstash:8.8.1
        resources:
          limits:
            memory: "1000Mi"
            cpu: "400m"
          requests:
            memory: "500Mi"
            cpu: "200m"
        ports:
        - containerPort: 5044
        volumeMounts:
          - mountPath: "/usr/share/logstash/config/logstash.yml"
            subPath: logstash.yml
            name: logstash-config
            readOnly: true

          - mountPath: "/usr/share/logstash/pipeline/logstash.conf"
            subPath: logstash.conf
            name: logstash-pipeline
            readOnly: true

      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config-cm
            items:
              - key: logstash.yml
                path: logstash.yml

        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline-cm
            items:
              - key: logstash.conf
                path: logstash.conf

---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: elastic-system
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.5.38.113
  selector:
    app: logstash
  ports:
  - port: 5044
    targetPort: 5044
